language: cpp

sudo: true

matrix:
  include:
    - os: linux
      env: COMPILER=g++-8 CCOMPILER=gcc-8
    - os: linux
      env: COMPILER=g++-9 CCOMPILER=gcc-9
    - os: linux
      env: COMPILER=g++ CCOMPILER=gcc 
    - os: linux
      env: COMPILER=clang++-5 CCOMPILER=clang-5
    - os: linux
      env: COMPILER=clang++-6 CCOMPILER=clang-6
    - os: linux
      env: COMPILER=clang++ CCOMPILER=clang
    - os: osx
  allow_failures:
    - env: COMPILER=clang++-3.6 CCOMPILER=clang-3.6
    - env: COMPILER=g++-4.9 CCOMPILER=gcc-4.9

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise
      - llvm-toolchain-precise-3.6
      - llvm-toolchain-precise-3.7
      - george-edison55-precise-backports
    packages:
      - g++-8
      - g++-9
      - clang-5
      - clang-6
      - cmake
      - libsdl2-dev
      - libsdl2-ttf-dev
      - libsdl2-mixer-dev
      - libglew-dev
      - freeglut3-dev
      - libxmu-dev
      - libxi-dev
      - libdevil-dev

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install sdl2    ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install sdl2_ttf; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install sdl2_mixer; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install glew    ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install freeglut; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install devil   ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CXX=$COMPILER CC=$CCOMPILER; fi
  - cmake --version
  - mkdir build
  - cd build
  - cmake -LAH ..

script:
  - make VERBOSE=1
  - make test