name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Get dependencies
      run: |
        sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
        sudo apt-get update -y -qq
        sudo apt-get install libsdl2-dev libsdl2-ttf-dev libsdl2-mixer-dev 
        sudo apt-get install libglew-dev freeglut3-dev 
        sudo apt-get install libxmu-dev libxi-dev 
        sudo apt-get install libdevil-dev
        sudo apt-get install gcc g++
    - name: Update submodules
      run: git submodule update --init --recursive
    - name: create build folder
      run: mkdir build
    - name: cmake
      run: cd build && cmake ../
    - name: make
      run: cd build && make
    - name: make test
      run: cd build && make test
